export const CHANGE_LOADING = "CHANGE_LOADING";

export const FETCH_ORDER_FULFILLED = "FETCH_ORDER_FULFILLED";
export const FETCH_ORDER_REJECTED = "FETCH_ORDER_REJECTED";
export const FETCH_ORDERS_LIST_FULFILLED = "FETCH_ORDERS_LIST_FULFILLED";
export const FETCH_ORDERS_LIST_REJECTED = "FETCH_ORDERS_LIST_REJECTED";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_ORDERS_LIST = "CLEAR_ORDERS_LIST";
